import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Aplicación Avisos',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="emerald">
      <body>{children}</body>
    </html>
  );
}
